apiVersion: v1
kind: Namespace
metadata:
  name: fdbhgdfghdfgh-prod
  labels:
    environment-id: env_ec69cbab-f6ef-452a-b4a2-721569baa540
    project-id: project_40e72d10-e91e-4399-a94e-904f52b090c2
    project-name: fdbhgdfghdfgh
    environment-name: prod
    organization-id: org_c50d7b26-1f2a-4a6e-b11e-469a86e002c8
